node:
  state:
    linear:
      coefs: [0, 3]
    poly1_interactions:
      coefs: [0, 3]
  output:
    gaussian_noise:
      rho: [0, 0.05]
    gamma_noise:
      rho: [0, 0.05]
    bernoulli:
      mean_: [0.1, 0.9]
      gamma: 0, 1
      rho: [0.01, 0.07]
edge:
  sigmoid:
    alpha: [1, 6]
    beta: [-0.8, 0.8]
    tau: 1, 3, 5
    rho: [0.05, 0.2]
  gaussian_rbf:
    alpha: [1, 6]
    beta: [-0.8, 0.8]
    tau: 1, 3, 5
    rho: [0.05, 0.2]
  beta_noise:
    rho: [0.05, 0.3]